recipesapi/recipesapi/__init__.py
"""
The flask application package.
"""

from flask import Flask, Blueprint
app = Flask(__name__)

from views import userpage
from recipes import recipespage
from api import recipesapi
app.register_blueprint(userpage)
app.register_blueprint(recipespage)
app.register_blueprint(recipesapi)

recipesapi/recipesapi/views.py
"""
Routes and views for the flask application.
"""

from datetime import datetime
from flask import Flask, request, session, g, redirect, url_for, abort, \
     render_template, flash, Blueprint
from recipesapi import app
import md5
from sqlite3 import dbapi2 as sqlite3
from recipesdb import *
import hashlib


userpage = Blueprint('userpage',__name__)
@userpage.route('/')
@userpage.route('/home')
def home():
    db = get_db()
    cur = db.execute('select * from recipes limit 10')
    recipes = cur.fetchall()
    db = get_db()
    cur = db.execute('select * from users limit 10')
    users = cur.fetchall()
    return render_template('index.html', title='Home', year=datetime.now().year, users = users, recipes = recipes)


@userpage.route('/userslist')
def userhome():    
    db = get_db()
    cur = db.execute('select * from users')
    users = cur.fetchall()
    return render_template(
        'userlist.html',
        title='Users List',
        year=datetime.now().year,
        users = users
    )

@userpage.route('/adduserform')
def adduserform():    
    return render_template(
        'adduser.html',
        title='Add User',
        year=datetime.now().year,
    )

@userpage.route('/adduser', methods=['POST'])
def adduser():    
    username = request.form['username']
    password = request.form['password']
    confirmpassword = request.form['confirmpassword']
    
    if password == confirmpassword:               
        db = get_db()
        db.execute('insert into users (username, password) values (?,?)',(username, hashlib.sha256(password).hexdigest()))
        db.commit()
    return redirect(url_for('userpage.userhome'))

@userpage.route('/edituserform/<userid>')
def edituserform(userid=None):    
    return render_template(
        'edituser.html',
        title='Edit User',
        year=datetime.now().year,
        userid = userid
    )

@userpage.route('/edituser', methods=['POST'])
def edituser():    
    username = request.form['username']
    password = request.form['password']
    confirmpassword = request.form['confirmpassword']
    userid = request.form['userid']
    if password == confirmpassword:
        db = get_db()
        m = hashlib.md5()
        m.update(password)
        hashedpassword = m.digest()
        db.execute('update users set username=?,password=? where id=?',(username, hashlib.sha256(password).hexdigest(), userid))
        db.commit()
    return redirect(url_for('userpage.userhome'))

@userpage.route('/deleteuser/<userid>')
def deleteuser(userid=None):    
    db = get_db()
    db.execute('delete from users where id=?', userid)
    db.commit()
    return redirect(url_for('userpage.userhome'))

recipesapi/recipesapi/templates/addrecipe.html
{% extends "layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<h3>{{ message }}</h3>

<form action="{{url_for('recipespage.addrecipe')}}" method="post" enctype="multipart/form-data">
    <label>Title</label><br />
    <input type="text" name="title" /><br />
    <label>Text</label><br />
    <textarea name="text" style="width:100%; height:200px"></textarea><br />
    <label>Image</label><br />
    <input type="file" name="image" /><br />
    <input type="submit" value="Submit" />
</form>

{% endblock %}

recipesapi/recipesapi/templates/adduser.html
{% extends "layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<h3>{{ message }}</h3>

<form action="{{url_for('userpage.adduser')}}" method="post" enctype="multipart/form-data">
    <label>User Name</label><br />
    <input type="text" name="username" /><br />
    <label>Password</label><br />
    <input type="password" name="password" /><br />
    <label>Confirm Password</label><br />
    <input type="password" name="confirmpassword" /><br />
    <br />
    <input type="submit" value="Submit" />
</form>

{% endblock %}

recipesapi/recipesapi/templates/editrecipe.html
{% extends "layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<h3>{{ message }}</h3>

<form action="{{url_for('recipespage.editrecipe')}}" method="post" enctype="multipart/form-data">
    <label>Title</label><br />
    <input type="text" name="title" /><br />
    <label>Text</label><br />
    <textarea name="text" style="width:100%; height:200px"></textarea><br />
    <label>Image</label><br />
    <input type="file" name="image" /><br />
    <input type="hidden" name="recipeid" value="{{recipeid}}" /><br />
    <input type="submit" value="Submit" />
</form>

{% endblock %}

recipesapi/recipesapi/templates/edituser.html
{% extends "layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<form action="{{url_for('userpage.edituser')}}" method="post" enctype="multipart/form-data">
    <label>User Name</label><br />
    <input type="text" name="username" /><br />
    <label>Password</label><br />
    <input type="password" name="password" /><br />
    <label>Confirm Password</label><br />
    <input type="password" name="confirmpassword" /><br />
    <input type="hidden" value="{{userid}}" />
    <br />
    <input type="submit" value="Submit" />
</form>

{% endblock %}

recipesapi/recipesapi/templates/index.html
{% extends "layout.html" %}

{% block content %}

<h1>Top 10 Users</h1>
<table class="table">
    <tr>
        <th>User Name</th>
        <th>Edit</th>
        <th>Delete</th>        
    </tr>
    {% for u in users %}
    <tr>
        <td>{{u.username}}</td>
        <td><a href="{{url_for('userpage.edituser', userid=u.id)}}">Edit</a></td>
        <td><a href="{{url_for('userpage.deleteuser', userid=u.id)}}">Delete</a></td>
    </tr>
    {% endfor %}
</table>

<h1>Top 10 Recipes</h1>
<table class="table">
    <tr>
        <th>Title</th>
        <th>Text</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    {% for r in recipes %}
    <tr>
        <td>{{r.title}}</td>
        <td>{{r.text}}</td>
        <td><a href="{{url_for('recipespage.editrecipeform', recipeid=r.id) }}">Edit</a></td>
        <td><a href="{{url_for('recipespage.deleterecipe', recipeid=r.id) }}">Delete</a></td>
    </tr>
    {% endfor %}
</table>



{% endblock %}

recipesapi/recipesapi/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Recipes App</title>
    <link rel="stylesheet" type="text/css" href="/static/content/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/static/content/site.css" />
    <script src="/static/scripts/modernizr-2.6.2.js"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Recipes</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">                    
                    <li><a href="{{ url_for('userpage.adduserform') }}">Add User</a></li>
                    <li><a href="{{ url_for('recipespage.addrecipeform')}}">Add Recipe</a></li>
                    <li><a href="{{ url_for('userpage.userhome') }}">Users List</a></li>
                    <li><a href="{{ url_for('recipespage.recipehome') }}">Recipes List</a></li>
                    
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        {% block content %}{% endblock %}
        <hr />
        <footer>
            <p>&copy; {{ year }} - Recipes</p>
        </footer>
    </div>

    <script src="/static/scripts/jquery-1.10.2.js"></script>
    <script src="/static/scripts/bootstrap.js"></script>
    <script src="/static/scripts/respond.js"></script>
    {% block scripts %}{% endblock %}

</body>
</html>

recipesapi/recipesapi/templates/recipelist.html
{% extends "layout.html" %}

{% block content %}
<h1>{{title}}</h1>
<table class="table">
    <tr>
        <th>Title</th>
        <th>Text</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    {% for r in recipes %}
    <tr>
        <td>{{r.title}}</td>
        <td>{{r.text}}</td>
        <td><a href="{{url_for('recipespage.editrecipeform', recipeid=r.id) }}">Edit</a></td>
        <td><a href="{{url_for('recipespage.deleterecipe', recipeid=r.id) }}">Delete</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

recipesapi/recipesapi/templates/userlist.html
{% extends "layout.html" %}

{% block content %}
<h1>{{title}}</h1>
<table class="table">
    <tr>
        <th>User Name</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    {% for u in users %}
    <tr>
        <td>{{u.username}}</td>        
        <td><a href="{{url_for('userpage.edituser', userid=u.id)}}">Edit</a></td>
        <td><a href="{{url_for('userpage.deleteuser', userid=u.id)}}">Delete</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}